# LDAP login module strings.

auth.ldap.useridLable = User Name 
auth.ldap.passwordLable = Password
auth.ldap.organizationLable = Organization

# LDAP login module strings.
module.ldap.error.failToLogin= Fail to login: 
module.ldap.error.optionMissing=option missing
module.ldap.error.nullCallbackHandler=No CallbackHandler available.
module.ldap.error.moreItemsMatched=More than one object matched in LDAP
module.ldap.error.moreRolesMatched=More than one role found in LDAP

module.ldap.error.userNotFound=User not found.
module.ldap.error.roleNotFound=Role not found.
module.ldap.error.missingBaseDN=Missing base DN.
module.ldap.error.missingSearchQuery=Missing search query
module.ldap.error.nullPassword=Password must not be Empty.
module.ldap.error.emptyEntry= must not be Empty.

# Passthru login module strings.
module.passthru.authResult.warning=Insecure Access: Login done using passthru login module. 
module.passthru.useridLabel=User Name:
module.passthru.passwordLabel=Password:
module.passthru.otherinfoLabel=Other Info:
module.passthru.error.baduser=Fail to login User: 
module.passthru.error.nullSubject = Subject must not be null

# Siteminder login module strings.
module.siteminder.error.emptyUserID=User name/id is empty
module.siteminder.error.NotAuthenticated = User is not authenticated


# Secureway login module strings.

