


#This file configures various transport layer properties for the CIS Client API


##################################################################################
##                                       SOAP SSL Configuration
###################################################################################

#Location of the SSL client keystore.
# If you are using SSL then you MUST import the certificate provided by the
# servers you wish to connect to into the client keystore using java keytool.
# Either fill in <CIS_HOME> correctly or provide the file name of a java
# keystore that you have created externally.

#ssl.client.keystore=<CIS_HOME>/conf/ssl/client.keystore


#Location of the SSL server keystore
#The server keystore is typically not going to be useful if you are
#using weblogic, websphere or webmethods server to host the server, since they
#all have their own built in key store. This keystore parameter is provided in case you want
#to configure your own server side ssl functionality. DO NOT UNCOMMENT THIS UNLESS YOU KNOW
# WHAT YOU ARE DOING

#ssl.server.keystore=<CIS_HOME>/conf/ssl/server.keystore




##################################################################################
##                                       WEBMETHODS Configuration
###################################################################################

client.webmethods.poolEntryExpirationTimeInSec=600

#################  SSL Configuration ################

#The properties here are read by CIS CCI clients only. If you are using SSL
#uncomment the properties below and provide the appropriate values.

#Location of the Webmethods certificate file
#ssl.client.webMethods.certificateFile=<wm_cert_file>

#Password for the certificate file. You can enter the password in encrypted form or
#unencrypted form by providing a value for the appropriate property

#ssl.client.webMethods.password=<unencrypted_password>
#ssl.client.webMethods.encryptedPassword=<encrypted_password>

#Distinguished Name to identify the WebMethods client
#ssl.client.webMethods.DN=<distinguished_name>

#Set this property to 'false' if you do not want data exchanges between the Broker and
#Broker Client to be scrambled. This property defaults to 'true'
#ssl.client.webMethods.encrypted=<enable_encryption>

#######################################################################################
#                                          PERSISTENCE CONFIGURATION
########################################################################################
# Set this property to 'true' if you want persistent connections to be created by default.
# when this is false, client has to explictly create a persistent connection programatically
# by creating connections through a CISPersistentConnectionSpec.
persistence.useAlways=false

#Sets the persistence storage medium. Legal values are none, file (default none)
persistence.type=none

#--------------------------------------------------------------------------------------
#            File Persistence configuration
#--------------------------------------------------------------------------------------
# The root directory for the storage used by the persistence store. Should
# be different for each JVM that expects to use file persistence.
# BE SURE TO USE FORWARD SLASHES IN FILE NAMES.
#file.storageroot=C:\temp

#######################################################################################
#                                        RELIABLE DELIVERY
#######################################################################################
#
# Use reliable transports: Legal values are 'whenPossible' or 'never' (default 'whenPossible')
transport.useReliable=whenPossible