log4j.appender.defaultAppender=org.apache.log4j.ConsoleAppender
log4j.appender.defaultAppender.layout=com.i2.cis.util.LogLayout
#log4j.rootCategory=warn, defaultAppender

log4j.category.com.i2=warn, defaultAppender
log4j.category.com.i2.cis.backbus=warn
log4j.category.com.i2.cis.util=warn
log4j.category.com.i2.cis.util.FileUtil=info
log4j.category.com.i2.logistics.util.jdbc=warn

