<?xml version="1.0" standalone='no'?>

<xsl:stylesheet 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:lxslt="http://xml.apache.org/xslt"
                xmlns:i2="com.i2.ui.web.xsl.xalan.XalanExtension"
                xmlns:i18n="com.i2.x2.xsl.extensions.i18n.I18NExtension"
                extension-element-prefixes="i2 i18n"
                version="1.0">
  
 <xsl:import href="../../../../../../core/xsl/page.xsl"/>
 <xsl:import href="../../../../../../core/xsl/container.xsl"/>
 <xsl:import href="../../../../../../core/xsl/validation.xsl"/>
 <xsl:import href="../../../../../xsl/code_master.xsl"/>
  
  <xsl:output method="html"/>
  
  
  <!-- Entry Point -->
  <!-- ********************************************************************** 
      *********************************************************************** -->
  <xsl:template match="RESPONSES" mode="content">
  
    <xsl:call-template name="include_javascript_account_code_segment"/>
  
    <xsl:apply-templates select="RESPONSE/CONTAINER" mode="container">
      <xsl:with-param name="content" select="RESPONSE"/>
    </xsl:apply-templates>

  </xsl:template>
  
  <!-- ********************************************************************** 
  *********************************************************************** --> 
  <xsl:template match="RESPONSE" mode="container_content">
    <table border="0" cellpadding="0" cellspacing="0" width="100%"><tr>
      <form name="form" method="post" target="appFrame">
	  <td>
        <!-- Body -->
      	  <table border="0" cellpadding="0" cellspacing="0" width="100%">
	        <tr><td  width="100%">
			  <input type="hidden" name="EDITABLE" value="{/RESPONSES/RESPONSE/EDITABLE/@Value}"/>
	          <xsl:apply-templates select="PAGE"/>
	        </td></tr>
         </table>
		 </td>
       </form>
     </tr>
   </table>
 </xsl:template>
 
 <!-- ********************************************************************** 
 *********************************************************************** -->
 <xsl:template match="PAGE">

    <xsl:variable name="caption">
      <i18n:text>Segments</i18n:text>
    </xsl:variable>

    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!--  This table exists for the sole purpose of eating  -->
    <!--  the newling generated by the form...              --> 
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <table width="100%" cellpadding="0" cellspacing="0">
      <tr>
	    <!--
        <form name="acctCodeForm" action="data/saveNewAccountCode.cmd" method="POST" target="appFrame">
		-->
          <input type="hidden" name="ORG_ID"     value="{ORG_ID/@Value}"/>
          <input type="hidden" name="PAGE"       value="account_codes_edit"/>
          <td>
            <i2:container inner="yes" title="{$caption}" id="types_container" >
              <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
              <!--  Header (right-aligned "arrange" image)                 -->
              <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
              <!-- ~~~~~~~Allow Edit only if Org in primary domain~~~~~~~~ -->
              <xsl:if test="PRIMARY_DOMAIN/@Value = 'true'">
                <i2:header>
                  <table border="0" cellpadding="2" cellspacing="0" width="100%">
                    <tr>
                      <td align="right">
                        <xsl:variable name="orgId" select="ORG_ID/@Value"/>
                        <xsl:variable name="arrangeUrl">
                          <xsl:value-of select="concat('arrangeAccountCodes.jsp?ORG_ID=', $orgId )"/>
                        </xsl:variable>
                        <a href="javascript:popupArrangeWindow( '{$arrangeUrl}' )">
                          <xsl:variable name="txtAltAttr"><i18n:text>Arrange</i18n:text></xsl:variable>
                          <i2:img src="/cstmz_actv.gif" alt="{$txtAltAttr}" border="0"/>
                        </a>
                      </td>
                    </tr>
                  </table>
                </i2:header>
              </xsl:if>
			  
              <xsl:call-template name="display_instruction_area">
			    <xsl:with-param name="pFormName" select="'form'"/>
			  	<xsl:with-param name="pAnyFieldIsRequired" select="'true'"/>
			  	<xsl:with-param name="pErrorMessage" select="../ERROR_MESSAGE/@Value"/>
			  	<xsl:with-param name="pSuccessMessage" select="../SUCCESS_MESSAGE/@Value"/>
        	  </xsl:call-template>
			  
              <xsl:choose>
                 <xsl:when test="(count(SEGMENT_TABLE/SEGMENT) = 0) and (PRIMARY_DOMAIN/@Value != 'true')">
                   <table>
                     <tr><td>
                       <i18n:text>No Account Code segments have been created for this Organization</i18n:text>
                     </td></tr>
                     <!-- blank-line -->
                     <tr><td>&#160;</td></tr>
                   </table>
                  </xsl:when>
                  <xsl:otherwise>
                    <i2:table scrollablerows="yes" scrollablecolumns="auto" id="types_table">
                    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
                    <!--  table column headers...       -->
                    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
                    <i2:tr header="yes">
                      <xsl:if test="PRIMARY_DOMAIN/@Value = 'true'">
                        <th nowrap="true" width="1%" class="checkboxColumn">        
                          <xsl:choose>
                            <xsl:when test="count(SEGMENT_TABLE/SEGMENT) > 0">
                              <input type="checkbox" name="SELECT_ALL" value="SELECT_ALL" onclick="javascript:toggleChecks(document.acctCodeForm)"/>
                            </xsl:when>
                            <xsl:otherwise>&#xA0;</xsl:otherwise>                     
                          </xsl:choose> 
                        </th>
                      </xsl:if>
                      <th align="left" nowrap="true">&#xA0;<i18n:text>Name</i18n:text></th>
                      <th align="left" nowrap="true">&#xA0;<i18n:text>Description</i18n:text></th>
                      <th align="left" nowrap="true">&#xA0;<i18n:text>Values</i18n:text></th>
                    </i2:tr>
                    <xsl:apply-templates select="SEGMENT_TABLE/SEGMENT" mode="edit" />
                    <xsl:if test="PRIMARY_DOMAIN/@Value = 'true'">
                      <xsl:call-template name="newSegment">
                        <xsl:with-param name="numRows" select="count(SEGMENT_TABLE/*)"/>
                      </xsl:call-template>
                    </xsl:if>
                  </i2:table>    
                </xsl:otherwise>
              </xsl:choose>
            </i2:container>
          </td>    
        <!-- </form> -->
      </tr>
    </table>

  </xsl:template>

  <!-- ********************************************************************** 
  *********************************************************************** -->
  <!--  Segment -->
  <xsl:template match="SEGMENT" mode="edit">
    <i2:tr>
      <input type="hidden" name="TYPE_ID" value="{TYPE_ID/@Value}"/> 
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- checkbox column                -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <xsl:if test="../../PRIMARY_DOMAIN/@Value = 'true'">
        <td nowrap="true" width="1%" class="checkboxColumn">
          <input type="checkbox" name="SELECTED" value="{TYPE_ID/@Value}"/>
        </td>
      </xsl:if>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- Segment Name column            -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true" width="10%" >
        <xsl:choose>
          <xsl:when test="../../PRIMARY_DOMAIN/@Value = 'true'">
            <input type="field" 
                 class="inputfieldIE" 
                 name="TYPE_VALUE_ID" 
                 value="{TYPE_VALUE_ID/@Value}" 
                 size="27" >
              <xsl:attribute name="tabIndex">
                <xsl:value-of select="(position() * 100) + 1"/>
              </xsl:attribute>
            </input>
          </xsl:when>
          <xsl:otherwise>
            <xsl:value-of select="TYPE_VALUE_ID/@Value"/>
          </xsl:otherwise>
        </xsl:choose> 
      </td>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- segment description            -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true">
        <xsl:choose>
          <xsl:when test="../../PRIMARY_DOMAIN/@Value = 'true'">
            <input type="field" 
                 class="inputfieldIE" 
                 name="DESCRIPTION" 
                 value="{DESCRIPTION/@Value}" 
                 size="47" >
            <xsl:attribute name="tabIndex">
              <xsl:value-of select="(position() * 100) + 2"/>
            </xsl:attribute>
          </input>
          </xsl:when>
          <xsl:otherwise>
            <xsl:value-of select="DESCRIPTION/@Value"/>
          </xsl:otherwise>
        </xsl:choose> 
      </td>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- values URL column              -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true" width="10%" >
        <a href="{VALUES_URL/@Value}" target="appFrame">
          <i18n:text>Values</i18n:text>
        </a>
      </td>
    </i2:tr>
  </xsl:template>

  <!-- ********************************************************************** 
  *********************************************************************** -->
  <!--  newSegment -->
  <xsl:template name="newSegment" mode="edit">
    <xsl:param name="numRows"/>
    <i2:tr>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- checkbox column                -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true" width="1%">
      </td>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- Segment Name column            -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true">
        <input type="field" 
               class="inputfieldIE" 
               name="NEW_TYPE_VALUE_ID" 
               size="27"
               required="true" >
          <xsl:attribute name="tabIndex">
            <xsl:value-of select="(($numRows+1) * 100) + 1"/>
          </xsl:attribute>
        </input>
        <xsl:call-template name="display_alert_mark"/>
        <xsl:call-template name="display_alert_image">
          <xsl:with-param name="fieldName" select="'NEW_TYPE_VALUE_ID'"/>
        </xsl:call-template>               
      </td>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- segment description            -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true">
        <input type="field" 
               class="inputfieldIE" 
               name="NEW_DESCRIPTION" 
               size="47"
               required="true" >
          <xsl:attribute name="tabIndex">
            <xsl:value-of select="(($numRows+1) * 100) + 2"/>
          </xsl:attribute>
        </input>
        <xsl:call-template name="display_alert_mark"/>
        <xsl:call-template name="display_alert_image">
          <xsl:with-param name="fieldName" select="'NEW_DESCRIPTION'"/>
        </xsl:call-template>               
      </td>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- values URL column              -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true" width="10%" >
      </td>
    </i2:tr>
  </xsl:template>
  
  <!-- page.xsl Javascript -->
  <!-- ********************************************************************** 
  *********************************************************************** -->
  <xsl:template name="onLoad_js">
    function onLoad()
    {
	  initSegTable();
      <xsl:call-template name="javascript_onLoad_tab"/>
      <xsl:call-template name="javascript_onLoad_page"/>
    }
  </xsl:template>


  <!-- ********************************************************************** 
  *********************************************************************** -->
  <xsl:template name="onResize_js">

    function onResize()
    {
	    initSegTable();
    	<xsl:call-template name="javascript_onResize_tab"/>
    	<xsl:call-template name="javascript_onResize_page"/>
    }
  </xsl:template>


  <!-- Javascript -->
  <!-- ********************************************************************** 
       *********************************************************************** -->
  <xsl:template name="javascript_onLoad_tab">
    <xsl:call-template name="javascript_resizeOrgTabs"/>
  </xsl:template>


  <!-- ********************************************************************** 
       *********************************************************************** -->
  <xsl:template name="javascript_onResize_tab">
    <xsl:call-template name="javascript_resizeOrgTabs"/>
  </xsl:template>
  
  <!-- overrides the js in tabs.xsl -->
  <!-- ********************************************************************** 
  *********************************************************************** -->
  <xsl:template name="javascript_resizeOrgTabs">  
    i2uiResizeScrollableContainer('container',document.body.offsetHeight - 90, null, document.body.offsetWidth - 40, true, 'yes');
    i2uiResizeScrollableContainer('tabs_container_description',document.body.offsetHeight -105, null, document.body.offsetWidth - 20, true, 'yes');
  </xsl:template>

   <!-- ********************************************************************** 
       *********************************************************************** -->
  <xsl:template name="include_javascript_account_code_segment">
    <script type="text/javascript">
	  function onUpdate()
	  {
    	  document.form.action= "segment/controller/update.cmd";
		  document.form.target="appFrame";
	  	  document.form.submit();
	  }
	  
	  function saveAsNew()
	  {
	    var bIsFormValid = isFormValid('form') ;
      	if ( bIsFormValid == true)
        {
    	  document.form.action= "segment/controller/save.cmd";
		  document.form.target="appFrame";
	  	  document.form.submit();
		}
  		return;
	  }
	  
	  function initSegTable()
	  {
  		initContainer('types_container');
  		if (!document.layers)
  		{
    		var x = document.body.scrollWidth - 34;
    		i2uiResizeScrollableArea('types_table',218,x,null,20);
    		i2uiResizeColumns('types_table');
    		i2uiCollapseTreeTable('types_table', 0, null, 1)    
  		}
  		initContainer('types_container');
	  }
	  
    </script>
  </xsl:template>
  
  <!-- ********************************************************************** 
       *********************************************************************** -->
  
</xsl:stylesheet>

