<?xml version="1.0" standalone='no'?>

<xsl:stylesheet 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:lxslt="http://xml.apache.org/xslt"
                xmlns:i2="com.i2.ui.web.xsl.xalan.XalanExtension"
                xmlns:i18n="com.i2.x2.xsl.extensions.i18n.I18NExtension"
                extension-element-prefixes="i2 i18n"
                version="1.0">
  
 <xsl:import href="../../../../../../core/xsl/page.xsl"/>
 <xsl:import href="../../../../../../core/xsl/container.xsl"/>
 <xsl:import href="../../../../../../core/xsl/validation.xsl"/>
 <xsl:import href="../../../../../xsl/code_master.xsl"/>
  
  <xsl:output method="html"/>
  
  
  <!-- Entry Point -->
  <!-- ********************************************************************** 
      *********************************************************************** -->
  <xsl:template match="RESPONSES" mode="content">
  
    <xsl:call-template name="include_javascript_account_code_value"/>
  
    <xsl:apply-templates select="RESPONSE/CONTAINER" mode="container">
      <xsl:with-param name="content" select="RESPONSE"/>
    </xsl:apply-templates>

  </xsl:template>
  
  <!-- ********************************************************************** 
  *********************************************************************** --> 
  <xsl:template match="RESPONSE" mode="container_content">
    <table border="0" cellpadding="0" cellspacing="0" width="100%"><tr>
      <form name="form" method="post" target="appFrame">
	  <td>
        <!-- Body -->
      	  <table border="0" cellpadding="0" cellspacing="0" width="100%">
	        <tr><td  width="100%">
	          <xsl:apply-templates select="VALUES_PAGE"/>
	        </td></tr>
         </table>
		 </td>
       </form>
     </tr>
   </table>
 </xsl:template>
 
 <!-- ********************************************************************** 
 *********************************************************************** -->
 <xsl:template match="VALUES_PAGE">

    <table width="100%">
      <!-- blank-line -->
      <tr><td>&#160;</td></tr>
      <tr>
        <!-- Label -->
        <td nowrap="true" width="1%" >
          <i18n:text>Account Code Segment:</i18n:text>
        </td>
		
        <!--<form name="combo">     -->
          <xsl:choose>
            <xsl:when test=" count(SEGMENT_TABLE/SEGMENT) &gt; 1" >
              <!-- options box -->
              <td>
                <select class="inputfieldIE" name="SELECTED_SEGMENT" onchange="javascript:onChangeSegment();" >
                  <xsl:apply-templates select="SEGMENT_TABLE/SEGMENT" mode="pulldown">
                    <xsl:with-param name="selectedId">
                      <xsl:value-of select="SEGMENT_ID/@Value"/>
                    </xsl:with-param>
                  </xsl:apply-templates>
                </select>
              </td>
            </xsl:when>
            <xsl:otherwise>
              <td>
                <xsl:value-of select="SEGMENT_TABLE/SEGMENT/TYPE_VALUE_ID/@Value"/>
              </td>
            </xsl:otherwise>
          </xsl:choose>
        <!--</form>-->
      </tr>
      <!-- blank-line -->
      <tr><td>&#160;</td></tr>
    </table>
    <xsl:variable name="caption">
      <i18n:text>Account Code Values</i18n:text>
    </xsl:variable>
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!--  This table exists for the sole purpose of eating  -->
    <!--  the newling generated by the form...              --> 
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <table width="100%" cellpadding="0" cellspacing="0">
      <tr>
	    <!--
        <form name="acctCodeValuesForm" 
          action="data/opActivationEdit.cmd" 
          method="POST" 
          target="appFrame">
		  -->
          <input type="hidden" name="ORG_ID"     value="{ORG_ID/@Value}"/>
          <input type="hidden" name="SEGMENT_ID" value="{SEGMENT_ID/@Value}"/>
          <input type="hidden" name="PAGE"       value="org_account_code_value"/>
          <td>
            <i2:container inner="yes" title="{$caption}" id="values_container" >
              <xsl:call-template name="display_instruction_area">
			    <xsl:with-param name="pFormName" select="'form'"/>
			  	<xsl:with-param name="pAnyFieldIsRequired" select="'true'"/>
			  	<xsl:with-param name="pErrorMessage" select="../ERROR_MESSAGE/@Value"/>
			  	<xsl:with-param name="pSuccessMessage" select="../SUCCESS_MESSAGE/@Value"/>
        	  </xsl:call-template>
			  
              <xsl:choose>
                <xsl:when test="(count(VALUES_TABLE/CODE_MASTER_VALUE) = 0) and (PRIMARY_DOMAIN/@Value != 'true')">
                  <table>
                    <tr><td>
                      <i18n:text>No Values Have Been Created For This Account Code Segment</i18n:text>
                    </td></tr>
                    <!-- blank-line -->
                    <tr><td>&#160;</td></tr>
                  </table>
                </xsl:when>
                <xsl:otherwise>
                  <i2:table scrollablerows="yes" scrollablecolumns="auto" id="values_table">
                    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
                    <!--  table column headers...       -->
                    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
                    <i2:tr header="yes">
                      <xsl:if test="PRIMARY_DOMAIN/@Value = 'true'">
                        <th nowrap="true" width="1%" class="checkboxColumn">       
                          <xsl:choose>
                          <xsl:when test="count(VALUES_TABLE/CODE_MASTER_VALUE) > 0">
                            <input type="checkbox" name="SELECT_ALL" value="SELECT_ALL" onclick="javascript:toggleChecks()"/> 
                          </xsl:when>
                          <xsl:otherwise>&#xA0;</xsl:otherwise>                     
                          </xsl:choose> 
                        </th>
                      </xsl:if>
                      <th align="left" nowrap="true">&#xA0;<i18n:text>Value</i18n:text></th>
                      <th align="left" nowrap="true">&#xA0;<i18n:text>Description</i18n:text></th>
                    </i2:tr>
                    <xsl:apply-templates select="VALUES_TABLE/CODE_MASTER_VALUE"/>
                    <xsl:if test="PRIMARY_DOMAIN/@Value = 'true'">
                      <xsl:call-template name="newValue">
                        <xsl:with-param name="numRows" select="count(VALUES_TABLE/*)"/>
                      </xsl:call-template>
                    </xsl:if>
                  </i2:table>    
                </xsl:otherwise>
              </xsl:choose>
			  <!--
              <i2:footer>
                <xsl:apply-templates select="BUTTONS"/>
              </i2:footer>
			  -->
            </i2:container>
          </td>    
        <!--</form>-->
      </tr>
    </table>

  </xsl:template>
  
  <!-- ********************************************************************** 
  *********************************************************************** -->
  <xsl:template match="CODE_MASTER_VALUE">
    <i2:tr>
      <input type="hidden" name="ID" value="{ID/@Value}"/> 
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- checkbox column                -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <xsl:if test="../../PRIMARY_DOMAIN/@Value = 'true'">
        <td nowrap="true" width="1%" class="checkboxColumn">
          <input type="checkbox" name="SELECTED" value="{ID/@Value}"/>
        </td>
      </xsl:if>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- segment value (Name) column    -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true" width="10%" >
        <xsl:choose>
          <xsl:when test="../../PRIMARY_DOMAIN/@Value = 'true'">
            <input type="field" 
                   class="inputfieldIE" 
                   name="VALUE_ID" 
                   value="{VALUE_ID/@Value}" 
                   size="27" >
              <xsl:attribute name="tabIndex">
                <xsl:value-of select="(position() * 100) + 1"/>
              </xsl:attribute>
            </input>
          </xsl:when>
          <xsl:otherwise>
            <xsl:value-of select="VALUE_ID/@Value"/>
          </xsl:otherwise>
        </xsl:choose> 
      </td>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- segment value description      -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true">
        <xsl:choose>
          <xsl:when test="../../PRIMARY_DOMAIN/@Value = 'true'">
            <input type="field" 
                   class="inputfieldIE" 
                   name="DESCRIPTION" 
                   value="{DESCRIPTION/@Value}" 
                   size="47" >
              <xsl:attribute name="tabIndex">
                <xsl:value-of select="(position() * 100) + 2"/>
              </xsl:attribute>
            </input>
          </xsl:when>
          <xsl:otherwise>
            <xsl:value-of select="DESCRIPTION/@Value"/>
          </xsl:otherwise>
        </xsl:choose> 
      </td>
    </i2:tr>

  </xsl:template>    

  <!-- ********************************************************************** 
  *********************************************************************** -->
  <xsl:template name="newValue" mode="edit">
    <xsl:param name="numRows"/>
    <i2:tr> 
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- checkbox column                -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true" width="1%">
      </td>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- segment value (Name) column    -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true" width="10%" >
        <input type="field" 
               class="inputfieldIE" 
               name="NEW_VALUE_ID" 
               size="27"
               required="true" >
          <xsl:attribute name="tabIndex">
            <xsl:value-of select="(($numRows+1) * 100) + 1"/>
          </xsl:attribute>
        </input>
        <xsl:call-template name="display_alert_mark"/>
        <xsl:call-template name="display_alert_image">
          <xsl:with-param name="fieldName" select="'NEW_VALUE_ID'"/>
        </xsl:call-template>               
      </td>
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <!-- segment value description      -->
      <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
      <td nowrap="true">
        <input type="field" 
               class="inputfieldIE" 
               name="NEW_DESCRIPTION" 
               size="47"
               required="true" >
          <xsl:attribute name="tabIndex">
            <xsl:value-of select="(($numRows+1) * 100) + 2"/>
          </xsl:attribute>
        </input>
        <xsl:call-template name="display_alert_mark"/>
        <xsl:call-template name="display_alert_image">
          <xsl:with-param name="fieldName" select="'NEW_DESCRIPTION'"/>
        </xsl:call-template>               
      </td>
    </i2:tr>
	
  </xsl:template>
  
  <!-- page.xsl Javascript -->
  <!-- ********************************************************************** 
  *********************************************************************** -->
  <xsl:template name="onLoad_js">
    function onLoad()
    {
	  initValueTable();
      <xsl:call-template name="javascript_onLoad_tab"/>
      <xsl:call-template name="javascript_onLoad_page"/>
    }
  </xsl:template>


  <!-- ********************************************************************** 
  *********************************************************************** -->
  <xsl:template name="onResize_js">

    function onResize()
    {
	    initValueTable();
    	<xsl:call-template name="javascript_onResize_tab"/>
    	<xsl:call-template name="javascript_onResize_page"/>
    }
  </xsl:template>


  <!-- Javascript -->
  <!-- ********************************************************************** 
       *********************************************************************** -->
  <xsl:template name="javascript_onLoad_tab">
    <xsl:call-template name="javascript_resizeTabs"/>
  </xsl:template>


  <!-- ********************************************************************** 
       *********************************************************************** -->
  <xsl:template name="javascript_onResize_tab">
    <xsl:call-template name="javascript_resizeTabs"/>
  </xsl:template>
  

   <!-- ********************************************************************** 
       *********************************************************************** -->
  <xsl:template name="include_javascript_account_code_value">
    <script type="text/javascript">

	  function onUpdate()
	  {
    	  document.form.action= "value/controller/update.cmd";
		  document.form.target="appFrame";
	  	  document.form.submit();
	  }
	  
	  function onDelete()
	  {
    	  document.form.action= "value/controller/delete.cmd";
		  document.form.target="appFrame";
	  	  document.form.submit();
	  }
		  
	  function onSave()
	  {
	    var bIsFormValid = isFormValid('form') ;
      	if ( bIsFormValid == true)
        {
    	  document.form.action= "value/controller/save.cmd";
		  document.form.target="appFrame";
	  	  document.form.submit();
		}
  		return;
	  }
	  
	  function onChangeSegment()
	  {
  		document.form.SEGMENT_ID.value = document.form.SELECTED_SEGMENT.value;
  		document.form.action = omxContextPath + "/omx/common/reload.cmd";
  		document.form.submit();
	  }
	  
	  function toggleChecks()
	  {
  		toggleCheckboxes( document.form, document.form.SELECTED, document.form.SELECT_ALL);
	  }
	  
	  function initValueTable()
	  {
  		initContainer('values_container');
  		if (!document.layers)
  		{
    		var x = document.body.scrollWidth - 34;
    		i2uiResizeScrollableArea('values_table',218,x,null,20);
    		i2uiResizeColumns('values_table');
    		i2uiCollapseTreeTable('values_table', 0, null, 1)    
  		}
  		initContainer('values_container');
	  }
	  
    </script>
  </xsl:template>
  
  <!-- ********************************************************************** 
       *********************************************************************** -->
  
</xsl:stylesheet>

